---
language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
  - "stable"

sudo: false

cache:
  directories:
    - node_modules

env:
  - TEST_FRAMEWORK=ember-cli-qunit EMBER_TRY_SCENARIO=default
  - TEST_FRAMEWORK=ember-cli-qunit EMBER_TRY_SCENARIO=ember-release
  - TEST_FRAMEWORK=ember-cli-qunit EMBER_TRY_SCENARIO=ember-beta
  - TEST_FRAMEWORK=ember-cli-qunit EMBER_TRY_SCENARIO=ember-canary
  - TEST_FRAMEWORK=ember-cli-mocha EMBER_TRY_SCENARIO=default
  - TEST_FRAMEWORK=ember-cli-mocha EMBER_TRY_SCENARIO=ember-release
  - TEST_FRAMEWORK=ember-cli-mocha EMBER_TRY_SCENARIO=ember-beta
  - TEST_FRAMEWORK=ember-cli-mocha EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

branches:
  only:
    - master

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install
  - ./bin/install-test-framework.sh

script:
  - npm run test:ci:cover

after_script:
  - npm install codeclimate-test-reporter
  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter
